service: sparcs-events-api

custom:
  projectName: sparcs-events
  serviceName: api
  stage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    dockerizePip: true
    layer:
      name: pwa-sls-${self:provider.stage}-python-requirements
      path: .
      compatibleRuntimes:
        - python3.8

package: ${file(resources/package.yml)}

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  memorySize: 3008
  versionFunctions: false
  timeout: 30
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Action: execute-api:Invoke
        Principal: "*"
        Resource: execute-api:/*/*/*
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.stage}
  logs:
    restApi: true

# resources:
#   - ${file(resources/cognito.yml)}

functions:
  - ${file(resources/api.yml)}

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
