service: sparcs-events-api

custom:
  projectName: sparcs-events
  serviceName: events
  stage: ${opt:stage, self:provider.stage}
  entities: ${self:custom.stage}-${self:custom.projectName}-entities
  bucket: ${self:custom.projectName}-bucket
  registrations: ${self:custom.stage}-${self:custom.projectName}-registrations
  emailQueue:
    !ImportValue EmailQueue-${self:provider.stage}
  basicAuthorizerARN:
    !ImportValue BasicAuthAuthorizerARN-${self:provider.stage}
  pythonRequirements:
    dockerizePip: non-linux
    layer:
      name: sparcs-events-${self:provider.stage}-python-requirements
      path: .
      compatibleRuntimes:
        - python3.8

package: ${file(resources/package.yml)}

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  memorySize: 3008
  versionFunctions: false
  timeout: 30
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Action: execute-api:Invoke
        Principal: "*"
        Resource: execute-api:/*/*/*
  s3:
    sparcsBucket:
      name: ${self:custom.bucket}
      versioningConfiguration:
        Status: Enabled
      corsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT]
            AllowedOrigins: ['*']
            Id: CORSRuleId1
            MaxAge: '3600'
      publicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.stage}
    ENTITIES_TABLE: ${self:custom.entities}
    REGISTRATIONS_TABLE: ${self:custom.registrations}
    EMAIL_QUEUE: ${self:custom.emailQueue}
    USER_POOL_ID:
      !ImportValue UserPoolId-${self:provider.stage}
    USER_POOL_CLIENT_ID:
      !ImportValue AppClientId-${self:provider.stage}
    SPARCS_GMAIL: sparcsup@gmail.com
  logs:
    restApi: true

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/api_gateway.yml)}

functions:
  - ${file(resources/api.yml)}
  - ${file(resources/s3.yml)}

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
