name: Deploy DurianPy Events Service
on:
  workflow_run:
    workflows: ["Backend Formatting Check on Push"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy (${{ (github.event.workflow_run.head_branch == 'main' || github.ref_name == 'main') && 'prod' || 'staging' }})
    if: >-
      (github.event_name == 'workflow_run' && 
       github.event.workflow_run.conclusion == 'success' && 
       (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'stage')) ||
      (github.event_name == 'workflow_dispatch' && 
       (github.ref_name == 'main' || github.ref_name == 'stage'))
    runs-on: ubuntu-latest
    environment: ${{ (github.event.workflow_run.head_branch == 'main' || github.ref_name == 'main') && 'prod' || 'staging' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Set ARN for Role to Assume
        run: |
          BRANCH="${{ github.event.workflow_run.head_branch || github.ref_name }}"
          if [[ "$BRANCH" == "main" ]]; then
            echo "AWS_OIDC_ROLE_ARN=${{ secrets.AWS_OIDC_ROLE_ARN_PROD }}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "stage" ]]; then
            echo "AWS_OIDC_ROLE_ARN=${{ secrets.AWS_OIDC_ROLE_ARN_STAGE }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: ap-southeast-1
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          role-session-name: GithubActionSession

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
        working-directory: backend

      - name: Install Serverless Framework
        run: |
          npm install
          npm install -g serverless@3.40.0
        working-directory: backend

      - name: Create requirements.txt
        run: uv export --format requirements-txt --no-hashes --output-file requirements.txt --no-dev
        working-directory: backend

      - name: Deploy with Serverless v3
        run: |
          BRANCH="${{ github.event.workflow_run.head_branch || github.ref_name }}"
          if [[ "$BRANCH" == "main" ]]; then
            sls deploy --stage prod --verbose
          elif [[ "$BRANCH" == "stage" ]]; then
            sls deploy --stage staging --verbose
          fi
        working-directory: backend
