name: Backend Formatting Check on Push

on:
  push:
    paths:
      - backend/**

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
            pip install flake8 black ruff
        working-directory: backend

      - name: Run Formatters
        run: |
            ruff check .
        working-directory: backend
